name: Drill Board Tracker
on: push

jobs:
  check-board-bounties:
    strategy:
      matrix:
        node: [17.6.0]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - id: config-repo
        name: Pre config - 🧰 Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: config-node
        name: Pre config - 🧰 Setting up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - id: install-dependencies
        run: npm ci

      - id: run-script
        run: node scripts/check-board.js
        env:
          RPC_ENDPOINT: ${{ secrets.RPC_ENDPOINT }}
          REPOSITORY_ID: ${{ secrets.REPOSITORY_ID }}
          PROGRAM_ID: ${{ secrets.PROGRAM_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_ID: ${{ secrets.APP_ID }}
          INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
