on: [push]

jobs:
  vault_updater_job:
    runs-on: ubuntu-latest
    name: A job to update all vaults' amounts.
    steps:
      - name: Vault Updater
        id: vault-updater
        uses: heavy-duty/drill-vault-updater-action@v1.0.0
        with:
          program-id: "2fg324Gf51Nrp1jzxXETvJmXPEiHz9ybNY1r575MtijW"
      - name: Get Result
        run: echo "The result was ${{ steps.vault-updater.result }}"
